### ISSUE TITLE
how to compile the chromium with debug information for GDB?

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#153]
from the print below, it seems the debug information was stripped in the final binary, so, how to get the callstack info properly with gdb debug tools?

tanks for your support.
#0  0x0000007f7f91c73c in epoll_pwait () from /lib/libc.so.6
#1  0x00000055782dc37c in ?? ()
#2  0x00000055782da6a0 in ?? ()
#3  0x000000557825342c in ?? ()
#4  0x0000005578277aa0 in ?? ()
#5  0x000000557815669c in ?? ()
#6  0x0000005576cc65e8 in ?? ()
#7  0x0000005576cc84f0 in ?? ()
#8  0x0000005576cc1f90 in ?? ()
#9  0x0000005577f07534 in ?? ()
#10 0x0000005577f11988 in ?? ()
#11 0x0000005577f05f74 in ?? ()
#12 0x000000557656f6a8 in ?? ()
#13 0x0000007f7f86fa24 in __libc_start_main () from /lib/libc.so.6
#14 0x000000557656f500 in ?? ()

**Comment by 13824125580** [comment]
thank you!
