### ISSUE TITLE
window_->surface() nullptr

### ISSUE THREAD

**Issue by fichter** [OSSystems/meta-browser#336]
I occasionally get a segfault with the following gdb backtrace. I can trigger it by rapidly clicking on many browser elements such as buttons.

It seems that in `wayland_buffer_manager_host.cc`, `window_->surface()` sometimes returns nullptr, which in `AttachAndDamageBuffer()` is passed to `wl_surface_damage_buffer()` causing the segfault.

The easiest workaround/fix is to check for it in the beginning of `CommitBufferInternal()`, like this:

```
bool CommitBufferInternal(WaylandBuffer* buffer) {
    DCHECK(buffer);
    DCHECK(!pending_buffer_);

+    if (window_->surface() == nullptr) {
+        LOG(ERROR) << "Window surface is null";
+        // Must return true, returning false causes TerminateGpuProcess().
+        return true;
+    }
```

I don't know if it safe to return true like this, or if this would just be classified as a hack, but the browser seems to behave ok for me.

Backtrace:
```
#0  0x7695547c in wl_proxy_marshal () from /usr/lib/libwayland-client.so.0
#1  0x00f0d2ea in wl_surface_damage_buffer ()
    at /usr/include/wayland-client-protocol.h:3754
#2  AttachAndDamageBuffer ()
    at ../../ui/ozone/platform/wayland/host/wayland_buffer_manager_host.cc:289
#3  0x00f0d202 in CommitBufferInternal ()
    at ../../ui/ozone/platform/wayland/host/wayland_buffer_manager_host.cc:248
#4  0x00f0c79a in CommitBuffer ()
    at ../../ui/ozone/platform/wayland/host/wayland_buffer_manager_host.cc:671
#5  0x00f1c1ca in Accept ()
    at gen/ui/ozone/public/mojom/wayland/wayland_buffer_manager.mojom.cc:587
#6  0x00a2490e in HandleValidatedMessage ()
    at ../../mojo/public/cpp/bindings/lib/interface_endpoint_client.cc:554
#7  0x00a24e34 in ProcessIncomingMessage ()
    at ../../mojo/public/cpp/bindings/lib/multiplex_router.cc:877
#8  0x02891bfc in ProcessTasks ()
    at ../../mojo/public/cpp/bindings/lib/multiplex_router.cc:712
#9  0x02892ad2 in LockAndCallProcessTasks ()
    at ../../mojo/public/cpp/bindings/lib/multiplex_router.cc:905
```

**Comment by msisov** [comment]
Please try with upstream version first. There were changes in that regards.
